### ISSUE TITLE
Unecessary newline for integrity constraints

### ISSUE THREAD

**Issue by MaxOstrowski** [sthiele/clingofmt#6]
```
:- a, b.
```
produces
```
:- 
    a,
    b.
```
but could be
```
:-  a,
    b.
```

**Comment by sthiele** [comment]
Strictly speaking the formatters job is adding unnecessary newlines. :smile:

**Comment by MaxOstrowski** [comment]
Actually this was a serious comment :smile: Is this newline intended ? Wouldn't it be better without ? ;)

**Comment by sthiele** [comment]
The issue was addressed in 0543d785c7d839144f840fc2ef03bd225664186b
